OSXVERS := 10.5
SDKVERS := 10.5
GUI := qt
ARCH = $(shell uname -p)
CPPFLAGS += -arch $(ARCH)  -mmacosx-version-min=$(OSXVERS)

LDFLAGS +=  -Wl,-arch,$(ARCH) -mmacosx-version-min=$(OSXVERS) -Wl,-syslibroot,/Developer/SDKs/MacOSX$(SDKVERS).sdk

include dismember.mk
